[package]
name = "sulla"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.26.2"
eframe = "0.26.2"
egui_dock = "0.11"
egui_extras = "0.26.2"

egui-file-dialog = "0.4"
